name = "mell"
version = "2.0.2"
author = "Diego Souza"
author_email = "diegofpsouza+mell@gmail.com"
url = "https://github.com/diegofps/pywup"
description = "A Metaprogramming Logic Layer designed to generate anything from template files"
